# direct domains
[direct]
"domain_suffix" = [
    # system
    "captive.apple.com",

    # Baidu
    "baidu.com",

    # Alibaba
    "aliyuncs.com",

    # Tencent
    "qq.com",
    "qcloudimg.com",
    "tencent.com",

    # Zhihu
    "zhihu.com",

    # Bytedance
    "byteimg.com",

    # Netease
    "163.com",

    # CSDN
    "csdn.net",

    # Bilibili
    "bilibili.com",

    # Steam
    "akamaihd.net",
    "steamcontent.com",

    # Other
    "dcarstatic.com",
    "sharon.io", # Sharon
]
